name: raj_eat
description: "A new Flutter project for food delivery"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-99.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Example of valid version constraint
  # Replace 'latest_version' with the actual version number if needed
  # plugin_name: ^1.0.0 (uncomment and use the correct version if necessary)
  cupertino_icons: ^1.0.6
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.7.7
  provider: ^6.1.2
  get: ^4.6.6
  fluttertoast: ^8.0.7
  location: ^7.0.0
  google_maps_flutter: ^2.0.0
  pay: ^2.0.0
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  firebase_messaging: ^14.9.4
  auto_size_text: ^3.0.0
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
